// <auto-generated />
using System;
using FiveAsideTournaments.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiveAsideTournaments.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260619160924_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiveAsideTournaments.Models.PaymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PaymentRecords");
                });

            modelBuilder.Entity("FiveAsideTournaments.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountOwed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric");

                    b.Property<string>("Attending")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOwed = 9.17m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Kyro",
                            Notes = "",
                            Paid = false,
                            TournamentId = 1
                        },
                        new
                        {
                            Id = 2,
                            AmountOwed = 9.17m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Reuben",
                            Notes = "",
                            Paid = false,
                            TournamentId = 1
                        },
                        new
                        {
                            Id = 3,
                            AmountOwed = 9.17m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Aakayan",
                            Notes = "",
                            Paid = false,
                            TournamentId = 1
                        },
                        new
                        {
                            Id = 4,
                            AmountOwed = 9.17m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Musa",
                            Notes = "",
                            Paid = false,
                            TournamentId = 1
                        },
                        new
                        {
                            Id = 5,
                            AmountOwed = 9.17m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Mason",
                            Notes = "",
                            Paid = false,
                            TournamentId = 1
                        },
                        new
                        {
                            Id = 6,
                            AmountOwed = 9.17m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Adam",
                            Notes = "",
                            Paid = false,
                            TournamentId = 1
                        },
                        new
                        {
                            Id = 7,
                            AmountOwed = 10.00m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Kyro",
                            Notes = "",
                            Paid = false,
                            TournamentId = 2
                        },
                        new
                        {
                            Id = 8,
                            AmountOwed = 10.00m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Reuben",
                            Notes = "",
                            Paid = false,
                            TournamentId = 2
                        },
                        new
                        {
                            Id = 9,
                            AmountOwed = 10.00m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Aakayan",
                            Notes = "",
                            Paid = false,
                            TournamentId = 2
                        },
                        new
                        {
                            Id = 10,
                            AmountOwed = 10.00m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Musa",
                            Notes = "",
                            Paid = false,
                            TournamentId = 2
                        },
                        new
                        {
                            Id = 11,
                            AmountOwed = 10.00m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Mason",
                            Notes = "",
                            Paid = false,
                            TournamentId = 2
                        },
                        new
                        {
                            Id = 12,
                            AmountOwed = 10.00m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Adam",
                            Notes = "",
                            Paid = false,
                            TournamentId = 2
                        },
                        new
                        {
                            Id = 13,
                            AmountOwed = 10.18m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Kyro",
                            Notes = "",
                            Paid = false,
                            TournamentId = 3
                        },
                        new
                        {
                            Id = 14,
                            AmountOwed = 10.18m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Reuben",
                            Notes = "",
                            Paid = false,
                            TournamentId = 3
                        },
                        new
                        {
                            Id = 15,
                            AmountOwed = 10.18m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Aakayan",
                            Notes = "",
                            Paid = false,
                            TournamentId = 3
                        },
                        new
                        {
                            Id = 16,
                            AmountOwed = 10.18m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Musa",
                            Notes = "",
                            Paid = false,
                            TournamentId = 3
                        },
                        new
                        {
                            Id = 17,
                            AmountOwed = 10.18m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Mason",
                            Notes = "",
                            Paid = false,
                            TournamentId = 3
                        },
                        new
                        {
                            Id = 18,
                            AmountOwed = 10.18m,
                            AmountPaid = 0m,
                            Attending = "unanswered",
                            Name = "Adam",
                            Notes = "",
                            Paid = false,
                            TournamentId = 3
                        });
                });

            modelBuilder.Entity("FiveAsideTournaments.Models.SeedPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountOwed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("SeedPlayers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOwed = 0m,
                            AmountPaid = 0m,
                            Name = "Reuben",
                            Notes = "",
                            Paid = false
                        },
                        new
                        {
                            Id = 2,
                            AmountOwed = 0m,
                            AmountPaid = 0m,
                            Name = "Mason",
                            Notes = "",
                            Paid = false
                        },
                        new
                        {
                            Id = 3,
                            AmountOwed = 0m,
                            AmountPaid = 0m,
                            Name = "Adam",
                            Notes = "",
                            Paid = false
                        },
                        new
                        {
                            Id = 4,
                            AmountOwed = 0m,
                            AmountPaid = 0m,
                            Name = "Kyro",
                            Notes = "",
                            Paid = false
                        },
                        new
                        {
                            Id = 5,
                            AmountOwed = 0m,
                            AmountPaid = 0m,
                            Name = "Musa",
                            Notes = "",
                            Paid = false
                        },
                        new
                        {
                            Id = 6,
                            AmountOwed = 0m,
                            AmountPaid = 0m,
                            Name = "Aakayan",
                            Notes = "",
                            Paid = false
                        });
                });

            modelBuilder.Entity("FiveAsideTournaments.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerPlayer")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPerPlayer = 9.17m,
                            Date = new DateTime(2026, 6, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "JOAP Rising Cup",
                            Notes = ""
                        },
                        new
                        {
                            Id = 2,
                            CostPerPlayer = 10.00m,
                            Date = new DateTime(2026, 6, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "FPF Tournament",
                            Notes = ""
                        },
                        new
                        {
                            Id = 3,
                            CostPerPlayer = 10.18m,
                            Date = new DateTime(2026, 6, 14, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oxford City Hoops Tournament",
                            Notes = "Arrival 11:45 AM • Surface: 3G • Parking £5 (Card Only)"
                        });
                });

            modelBuilder.Entity("FiveAsideTournaments.Models.PaymentRecord", b =>
                {
                    b.HasOne("FiveAsideTournaments.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FiveAsideTournaments.Models.Player", b =>
                {
                    b.HasOne("FiveAsideTournaments.Models.Tournament", "Tournament")
                        .WithMany("Players")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FiveAsideTournaments.Models.Tournament", b =>
                {
                    b.OwnsOne("FiveAsideTournaments.Models.TournamentLocation", "Location", b1 =>
                        {
                            b1.Property<int>("TournamentId")
                                .HasColumnType("integer");

                            b1.Property<string>("Address")
                                .HasColumnType("text");

                            b1.Property<string>("MapUrl")
                                .HasColumnType("text");

                            b1.Property<string>("Parking")
                                .HasColumnType("text");

                            b1.HasKey("TournamentId");

                            b1.ToTable("Tournaments");

                            b1.WithOwner()
                                .HasForeignKey("TournamentId");

                            b1.HasData(
                                new
                                {
                                    TournamentId = 1,
                                    Address = "Barnhill High School, UB4 9LE",
                                    MapUrl = "",
                                    Parking = ""
                                },
                                new
                                {
                                    TournamentId = 2,
                                    Address = "Rectory Park, UB5 5FA",
                                    MapUrl = "",
                                    Parking = ""
                                },
                                new
                                {
                                    TournamentId = 3,
                                    Address = "Oxford City FC, Marsh Lane, Oxford, OX3 0NQ",
                                    MapUrl = "",
                                    Parking = "£5 (Card Only)"
                                });
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FiveAsideTournaments.Models.Tournament", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
